# Use postgres/postgres user/password credentials
version: '3.1'
services:
  redis:
    image: bitnami/redis:4.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - 6379:6379
    volumes:
      - /bitnami/redis
